/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthcheckRouteImport } from './routes/api/healthcheck'
import { Route as RestaurantsIdRouteRouteImport } from './routes/restaurants/$id/route'
import { Route as ManageIdRouteRouteImport } from './routes/manage.$id/route'
import { Route as RestaurantsIdIndexRouteImport } from './routes/restaurants/$id/index'
import { Route as ManageIdIndexRouteImport } from './routes/manage.$id/index'
import { Route as ManageIdUpcomingRouteImport } from './routes/manage.$id/upcoming'
import { Route as ManageIdTablesRouteImport } from './routes/manage.$id/tables'
import { Route as ManageIdSettingsRouteImport } from './routes/manage.$id/settings'
import { Route as ManageIdMenusRouteImport } from './routes/manage.$id/menus'
import { Route as ManageIdIngredientsRouteImport } from './routes/manage.$id/ingredients'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as RestaurantsIdReserveReservationIdRouteImport } from './routes/restaurants/$id/reserve.$reservationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthcheckRoute = ApiHealthcheckRouteImport.update({
  id: '/api/healthcheck',
  path: '/api/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRouteRoute = RestaurantsIdRouteRouteImport.update({
  id: '/restaurants/$id',
  path: '/restaurants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIdRouteRoute = ManageIdRouteRouteImport.update({
  id: '/manage/$id',
  path: '/manage/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdIndexRoute = RestaurantsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RestaurantsIdRouteRoute,
} as any)
const ManageIdIndexRoute = ManageIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageIdRouteRoute,
} as any)
const ManageIdUpcomingRoute = ManageIdUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => ManageIdRouteRoute,
} as any)
const ManageIdTablesRoute = ManageIdTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => ManageIdRouteRoute,
} as any)
const ManageIdSettingsRoute = ManageIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManageIdRouteRoute,
} as any)
const ManageIdMenusRoute = ManageIdMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => ManageIdRouteRoute,
} as any)
const ManageIdIngredientsRoute = ManageIdIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => ManageIdRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdReserveReservationIdRoute =
  RestaurantsIdReserveReservationIdRouteImport.update({
    id: '/reserve/$reservationId',
    path: '/reserve/$reservationId',
    getParentRoute: () => RestaurantsIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage/$id': typeof ManageIdRouteRouteWithChildren
  '/restaurants/$id': typeof RestaurantsIdRouteRouteWithChildren
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/manage/$id/ingredients': typeof ManageIdIngredientsRoute
  '/manage/$id/menus': typeof ManageIdMenusRoute
  '/manage/$id/settings': typeof ManageIdSettingsRoute
  '/manage/$id/tables': typeof ManageIdTablesRoute
  '/manage/$id/upcoming': typeof ManageIdUpcomingRoute
  '/manage/$id/': typeof ManageIdIndexRoute
  '/restaurants/$id/': typeof RestaurantsIdIndexRoute
  '/restaurants/$id/reserve/$reservationId': typeof RestaurantsIdReserveReservationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/manage/$id/ingredients': typeof ManageIdIngredientsRoute
  '/manage/$id/menus': typeof ManageIdMenusRoute
  '/manage/$id/settings': typeof ManageIdSettingsRoute
  '/manage/$id/tables': typeof ManageIdTablesRoute
  '/manage/$id/upcoming': typeof ManageIdUpcomingRoute
  '/manage/$id': typeof ManageIdIndexRoute
  '/restaurants/$id': typeof RestaurantsIdIndexRoute
  '/restaurants/$id/reserve/$reservationId': typeof RestaurantsIdReserveReservationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manage/$id': typeof ManageIdRouteRouteWithChildren
  '/restaurants/$id': typeof RestaurantsIdRouteRouteWithChildren
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/manage/$id/ingredients': typeof ManageIdIngredientsRoute
  '/manage/$id/menus': typeof ManageIdMenusRoute
  '/manage/$id/settings': typeof ManageIdSettingsRoute
  '/manage/$id/tables': typeof ManageIdTablesRoute
  '/manage/$id/upcoming': typeof ManageIdUpcomingRoute
  '/manage/$id/': typeof ManageIdIndexRoute
  '/restaurants/$id/': typeof RestaurantsIdIndexRoute
  '/restaurants/$id/reserve/$reservationId': typeof RestaurantsIdReserveReservationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manage/$id'
    | '/restaurants/$id'
    | '/api/healthcheck'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/manage/$id/ingredients'
    | '/manage/$id/menus'
    | '/manage/$id/settings'
    | '/manage/$id/tables'
    | '/manage/$id/upcoming'
    | '/manage/$id/'
    | '/restaurants/$id/'
    | '/restaurants/$id/reserve/$reservationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/healthcheck'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/manage/$id/ingredients'
    | '/manage/$id/menus'
    | '/manage/$id/settings'
    | '/manage/$id/tables'
    | '/manage/$id/upcoming'
    | '/manage/$id'
    | '/restaurants/$id'
    | '/restaurants/$id/reserve/$reservationId'
  id:
    | '__root__'
    | '/'
    | '/manage/$id'
    | '/restaurants/$id'
    | '/api/healthcheck'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/manage/$id/ingredients'
    | '/manage/$id/menus'
    | '/manage/$id/settings'
    | '/manage/$id/tables'
    | '/manage/$id/upcoming'
    | '/manage/$id/'
    | '/restaurants/$id/'
    | '/restaurants/$id/reserve/$reservationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageIdRouteRoute: typeof ManageIdRouteRouteWithChildren
  RestaurantsIdRouteRoute: typeof RestaurantsIdRouteRouteWithChildren
  ApiHealthcheckRoute: typeof ApiHealthcheckRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthcheck': {
      id: '/api/healthcheck'
      path: '/api/healthcheck'
      fullPath: '/api/healthcheck'
      preLoaderRoute: typeof ApiHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/restaurants/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$id': {
      id: '/manage/$id'
      path: '/manage/$id'
      fullPath: '/manage/$id'
      preLoaderRoute: typeof ManageIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id/': {
      id: '/restaurants/$id/'
      path: '/'
      fullPath: '/restaurants/$id/'
      preLoaderRoute: typeof RestaurantsIdIndexRouteImport
      parentRoute: typeof RestaurantsIdRouteRoute
    }
    '/manage/$id/': {
      id: '/manage/$id/'
      path: '/'
      fullPath: '/manage/$id/'
      preLoaderRoute: typeof ManageIdIndexRouteImport
      parentRoute: typeof ManageIdRouteRoute
    }
    '/manage/$id/upcoming': {
      id: '/manage/$id/upcoming'
      path: '/upcoming'
      fullPath: '/manage/$id/upcoming'
      preLoaderRoute: typeof ManageIdUpcomingRouteImport
      parentRoute: typeof ManageIdRouteRoute
    }
    '/manage/$id/tables': {
      id: '/manage/$id/tables'
      path: '/tables'
      fullPath: '/manage/$id/tables'
      preLoaderRoute: typeof ManageIdTablesRouteImport
      parentRoute: typeof ManageIdRouteRoute
    }
    '/manage/$id/settings': {
      id: '/manage/$id/settings'
      path: '/settings'
      fullPath: '/manage/$id/settings'
      preLoaderRoute: typeof ManageIdSettingsRouteImport
      parentRoute: typeof ManageIdRouteRoute
    }
    '/manage/$id/menus': {
      id: '/manage/$id/menus'
      path: '/menus'
      fullPath: '/manage/$id/menus'
      preLoaderRoute: typeof ManageIdMenusRouteImport
      parentRoute: typeof ManageIdRouteRoute
    }
    '/manage/$id/ingredients': {
      id: '/manage/$id/ingredients'
      path: '/ingredients'
      fullPath: '/manage/$id/ingredients'
      preLoaderRoute: typeof ManageIdIngredientsRouteImport
      parentRoute: typeof ManageIdRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id/reserve/$reservationId': {
      id: '/restaurants/$id/reserve/$reservationId'
      path: '/reserve/$reservationId'
      fullPath: '/restaurants/$id/reserve/$reservationId'
      preLoaderRoute: typeof RestaurantsIdReserveReservationIdRouteImport
      parentRoute: typeof RestaurantsIdRouteRoute
    }
  }
}

interface ManageIdRouteRouteChildren {
  ManageIdIngredientsRoute: typeof ManageIdIngredientsRoute
  ManageIdMenusRoute: typeof ManageIdMenusRoute
  ManageIdSettingsRoute: typeof ManageIdSettingsRoute
  ManageIdTablesRoute: typeof ManageIdTablesRoute
  ManageIdUpcomingRoute: typeof ManageIdUpcomingRoute
  ManageIdIndexRoute: typeof ManageIdIndexRoute
}

const ManageIdRouteRouteChildren: ManageIdRouteRouteChildren = {
  ManageIdIngredientsRoute: ManageIdIngredientsRoute,
  ManageIdMenusRoute: ManageIdMenusRoute,
  ManageIdSettingsRoute: ManageIdSettingsRoute,
  ManageIdTablesRoute: ManageIdTablesRoute,
  ManageIdUpcomingRoute: ManageIdUpcomingRoute,
  ManageIdIndexRoute: ManageIdIndexRoute,
}

const ManageIdRouteRouteWithChildren = ManageIdRouteRoute._addFileChildren(
  ManageIdRouteRouteChildren,
)

interface RestaurantsIdRouteRouteChildren {
  RestaurantsIdIndexRoute: typeof RestaurantsIdIndexRoute
  RestaurantsIdReserveReservationIdRoute: typeof RestaurantsIdReserveReservationIdRoute
}

const RestaurantsIdRouteRouteChildren: RestaurantsIdRouteRouteChildren = {
  RestaurantsIdIndexRoute: RestaurantsIdIndexRoute,
  RestaurantsIdReserveReservationIdRoute:
    RestaurantsIdReserveReservationIdRoute,
}

const RestaurantsIdRouteRouteWithChildren =
  RestaurantsIdRouteRoute._addFileChildren(RestaurantsIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageIdRouteRoute: ManageIdRouteRouteWithChildren,
  RestaurantsIdRouteRoute: RestaurantsIdRouteRouteWithChildren,
  ApiHealthcheckRoute: ApiHealthcheckRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
