/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantsRouteRouteImport } from './routes/restaurants/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthcheckRouteImport } from './routes/api/healthcheck'
import { Route as RestaurantsIdRouteRouteImport } from './routes/restaurants/$id/route'
import { Route as ManageIdRouteRouteImport } from './routes/manage.$id/route'
import { Route as ManageIdSettingsRouteImport } from './routes/manage.$id/settings'
import { Route as ManageIdMenusRouteImport } from './routes/manage.$id/menus'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const RestaurantsRouteRoute = RestaurantsRouteRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthcheckRoute = ApiHealthcheckRouteImport.update({
  id: '/api/healthcheck',
  path: '/api/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRouteRoute = RestaurantsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RestaurantsRouteRoute,
} as any)
const ManageIdRouteRoute = ManageIdRouteRouteImport.update({
  id: '/manage/$id',
  path: '/manage/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIdSettingsRoute = ManageIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManageIdRouteRoute,
} as any)
const ManageIdMenusRoute = ManageIdMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => ManageIdRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/restaurants': typeof RestaurantsRouteRouteWithChildren
  '/manage/$id': typeof ManageIdRouteRouteWithChildren
  '/restaurants/$id': typeof RestaurantsIdRouteRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/manage/$id/menus': typeof ManageIdMenusRoute
  '/manage/$id/settings': typeof ManageIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/restaurants': typeof RestaurantsRouteRouteWithChildren
  '/manage/$id': typeof ManageIdRouteRouteWithChildren
  '/restaurants/$id': typeof RestaurantsIdRouteRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/manage/$id/menus': typeof ManageIdMenusRoute
  '/manage/$id/settings': typeof ManageIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/restaurants': typeof RestaurantsRouteRouteWithChildren
  '/manage/$id': typeof ManageIdRouteRouteWithChildren
  '/restaurants/$id': typeof RestaurantsIdRouteRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/manage/$id/menus': typeof ManageIdMenusRoute
  '/manage/$id/settings': typeof ManageIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/restaurants'
    | '/manage/$id'
    | '/restaurants/$id'
    | '/api/healthcheck'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/manage/$id/menus'
    | '/manage/$id/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/restaurants'
    | '/manage/$id'
    | '/restaurants/$id'
    | '/api/healthcheck'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/manage/$id/menus'
    | '/manage/$id/settings'
  id:
    | '__root__'
    | '/'
    | '/restaurants'
    | '/manage/$id'
    | '/restaurants/$id'
    | '/api/healthcheck'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/manage/$id/menus'
    | '/manage/$id/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RestaurantsRouteRoute: typeof RestaurantsRouteRouteWithChildren
  ManageIdRouteRoute: typeof ManageIdRouteRouteWithChildren
  ApiHealthcheckRoute: typeof ApiHealthcheckRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthcheck': {
      id: '/api/healthcheck'
      path: '/api/healthcheck'
      fullPath: '/api/healthcheck'
      preLoaderRoute: typeof ApiHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteRouteImport
      parentRoute: typeof RestaurantsRouteRoute
    }
    '/manage/$id': {
      id: '/manage/$id'
      path: '/manage/$id'
      fullPath: '/manage/$id'
      preLoaderRoute: typeof ManageIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$id/settings': {
      id: '/manage/$id/settings'
      path: '/settings'
      fullPath: '/manage/$id/settings'
      preLoaderRoute: typeof ManageIdSettingsRouteImport
      parentRoute: typeof ManageIdRouteRoute
    }
    '/manage/$id/menus': {
      id: '/manage/$id/menus'
      path: '/menus'
      fullPath: '/manage/$id/menus'
      preLoaderRoute: typeof ManageIdMenusRouteImport
      parentRoute: typeof ManageIdRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RestaurantsRouteRouteChildren {
  RestaurantsIdRouteRoute: typeof RestaurantsIdRouteRoute
}

const RestaurantsRouteRouteChildren: RestaurantsRouteRouteChildren = {
  RestaurantsIdRouteRoute: RestaurantsIdRouteRoute,
}

const RestaurantsRouteRouteWithChildren =
  RestaurantsRouteRoute._addFileChildren(RestaurantsRouteRouteChildren)

interface ManageIdRouteRouteChildren {
  ManageIdMenusRoute: typeof ManageIdMenusRoute
  ManageIdSettingsRoute: typeof ManageIdSettingsRoute
}

const ManageIdRouteRouteChildren: ManageIdRouteRouteChildren = {
  ManageIdMenusRoute: ManageIdMenusRoute,
  ManageIdSettingsRoute: ManageIdSettingsRoute,
}

const ManageIdRouteRouteWithChildren = ManageIdRouteRoute._addFileChildren(
  ManageIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RestaurantsRouteRoute: RestaurantsRouteRouteWithChildren,
  ManageIdRouteRoute: ManageIdRouteRouteWithChildren,
  ApiHealthcheckRoute: ApiHealthcheckRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
